# Pre-commit hooks configuration
# See https://pre-commit.com for more information
#
# To install: pre-commit install
# To run manually: pre-commit run --all-files

repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
      - id: check-json
        name: Check JSON syntax
      - id: check-toml
        name: Check TOML syntax
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: detect-private-key
        name: Detect private keys
      - id: debug-statements
        name: Check for debug statements
      - id: check-docstring-first
        name: Check docstring is first

  # Local hooks using uv commands
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check (linting)
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: true
        require_serial: false

      - id: ruff-format
        name: Ruff format check
        entry: uv run ruff format --check
        language: system
        types: [python]
        pass_filenames: true
        require_serial: false

      - id: type-check
        name: Type checking with ty
        entry: uv run ty check
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
        always_run: true

      - id: test-unit
        name: Run unit tests
        entry: uv run pytest tests/unit/ -x -q
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: Security check with Bandit
        args: ['-ll', '--skip', 'B101,B601']
        exclude: tests/

  # Documentation
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: Check docstring style
        exclude: tests/
        additional_dependencies: [toml]

# Configuration for hooks
default_language_version:
  python: python3.12

# Stages configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: 3.0.0